# Generated by Django 5.2 on 2025-05-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_montant_initial_payment_reduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='methode_paiement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
