# Generated by Django 5.2 on 2025-05-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_methode_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='methode_paiement',
            field=models.CharField(blank=True, choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('mtn_money', 'MTN Money'), ('espèces', 'Espèces'), ('autre', 'Autre')], max_length=50, null=True),
        ),
    ]
