# Generated by Django 5.2.17 on 2026-10-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_geniuspay_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentattempt',
            name='payment',
        ),
        migrations.DeleteModel(
            name='PaymentGatewayEvent',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='pay_provider_state_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='checkout_url',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='failed_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='initiated_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='provider_payload',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='provider_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='provider_status',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Référence fournie par l’artisan (Wave, Orange Money, virement, etc.).', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='statut',
            field=models.CharField(choices=[('unpaid', 'Non payé'), ('paid', 'Payé')], db_index=True, default='unpaid', max_length=16),
        ),
        migrations.DeleteModel(
            name='PaymentAttempt',
        ),
    ]
