# Generated by Django 5.2 on 2025-04-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lien_redirection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
