# Generated by Django 5.2 on 2025-05-11 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_commentaire_client_and_more'),
        ('notifications', '0002_notification_lien_redirection'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='rendez_vous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
        ),
    ]
