# Generated by Django 5.2 on 2025-05-11 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_rendez_vous'),
        ('services', '0003_alter_service_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
