# Generated by Django 5.2 on 2025-04-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='numero_momo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qr_wave',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
