import { useEffect, useState } from 'react';
import axios from '../../utils/axiosInstance';
import useAutoRefresh from '../../hooks/useAutoRefresh';

export default function AdminSupportPage() {
  const [items,setItems]=useState([]); const [filter,setFilter]=useState(''); const [message,setMessage]=useState('');
  const load=async()=>{try{const r=await axios.get('/support/admin/',{params:filter?{status:filter}:{}});setItems(r.data||[]);}catch{setMessage('Impossible de charger le support.');}};
  useEffect(()=>{load();},[filter]);
  useAutoRefresh(load, { intervalMs: 20000 });
  const update=async(item)=>{const statut=window.prompt('Statut : new, in_progress, waiting_user, resolved, closed',item.statut)||item.statut;const admin_response=window.prompt('Réponse à l’utilisateur',item.admin_response||'')??item.admin_response;try{await axios.patch(`/support/admin/${item.id}/`,{statut,priorite:item.priorite,admin_response});await load();setMessage('Demande mise à jour.');}catch(e){setMessage(e?.response?.data?.detail||'Action impossible.');}};
  return <div className="mx-auto max-w-[1350px] space-y-6 p-4 sm:p-6 lg:p-8"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#0B6B50]">Assistance</p><h1 className="mt-2 text-3xl font-black">Support utilisateurs</h1></div>{message&&<p className="rounded-2xl bg-[#EDF4FF] p-3 text-sm font-semibold text-[#3565A8]">{message}</p>}<select value={filter} onChange={(e)=>setFilter(e.target.value)} className="rounded-2xl border border-black/10 bg-white px-4 py-3 text-sm"><option value="">Tous</option><option value="new">Nouveaux</option><option value="in_progress">En cours</option><option value="waiting_user">Attente utilisateur</option><option value="resolved">Résolus</option><option value="closed">Fermés</option></select><div className="grid gap-3">{items.map(item=><article key={item.id} className="rounded-[24px] border border-black/5 bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-black">#{item.id} · {item.objet}</h2><p className="text-sm text-[#718078]">{item.requester_username} · {item.requester_role} · priorité {item.priorite_label}</p></div><span className="h-fit rounded-full bg-[#F1F4F2] px-3 py-1 text-xs font-bold">{item.statut_label}</span></div><p className="mt-3 text-sm leading-6">{item.message}</p>{item.admin_response&&<div className="mt-3 rounded-2xl bg-[#EAF4F0] p-3 text-sm"><strong>Réponse :</strong> {item.admin_response}</div>}<button onClick={()=>update(item)} className="mt-4 rounded-xl bg-[#10271F] px-4 py-2 text-xs font-black text-white">Traiter</button></article>)}</div></div>;
}
