import { useEffect, useState } from 'react';
import axios from '../../utils/axiosInstance';

const VERIF = { unverified: 'Non vérifié', pending: 'En vérification', verified: 'Vérifié', rejected: 'Refusé' };

export default function AdminUsersPage() {
  const [users, setUsers] = useState([]); const [search, setSearch] = useState(''); const [role, setRole] = useState(''); const [verification, setVerification] = useState(''); const [message, setMessage] = useState('');
  const load = async () => { try { const r = await axios.get('/moderation/admin/users/', { params: { search, role, verification } }); setUsers(r.data || []); } catch { setMessage('Impossible de charger les utilisateurs.'); } };
  useEffect(() => { const t = setTimeout(load, 250); return () => clearTimeout(t); }, [search, role, verification]);
  const action = async (user, name) => { let note = ''; if (['verify','reject'].includes(name)) note = window.prompt(name === 'verify' ? 'Note de validation (facultative)' : 'Motif du refus', '') || ''; if (!window.confirm(`Confirmer l’action « ${name} » sur ${user.username} ?`)) return; try { await axios.post(`/moderation/admin/users/${user.id}/action/`, { action: name, note }); setMessage('Action enregistrée.'); await load(); } catch (e) { setMessage(e?.response?.data?.detail || 'Action impossible.'); } };
  return <div className="mx-auto max-w-[1450px] space-y-6 p-4 sm:p-6 lg:p-8"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#0B6B50]">Comptes</p><h1 className="mt-2 text-3xl font-black">Utilisateurs</h1></div>{message && <p className="rounded-2xl bg-[#EDF4FF] p-3 text-sm font-semibold text-[#3565A8]">{message}</p>}<div className="grid gap-3 rounded-[24px] bg-white p-4 sm:grid-cols-3"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Rechercher nom ou email" className="rounded-2xl border border-black/10 px-4 py-3 text-sm"/><select value={role} onChange={(e) => setRole(e.target.value)} className="rounded-2xl border border-black/10 px-4 py-3 text-sm"><option value="">Tous les rôles</option><option value="client">Clients</option><option value="artisan">Artisans</option><option value="admin">Admins</option></select><select value={verification} onChange={(e) => setVerification(e.target.value)} className="rounded-2xl border border-black/10 px-4 py-3 text-sm"><option value="">Tous les statuts vérification</option><option value="pending">En vérification</option><option value="verified">Vérifiés</option><option value="rejected">Refusés</option><option value="unverified">Non vérifiés</option></select></div>
    <div className="grid gap-3">{users.map((user) => <article key={user.id} className="rounded-[24px] border border-black/5 bg-white p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-black">{user.username}</h2><span className="rounded-full bg-[#F1F4F2] px-2.5 py-1 text-xs font-bold uppercase">{user.role}</span>{!user.is_active && <span className="rounded-full bg-[#FFF0EE] px-2.5 py-1 text-xs font-black text-[#B23A31]">Suspendu</span>}{user.role === 'artisan' && <span className="rounded-full bg-[#FFF7DD] px-2.5 py-1 text-xs font-bold text-[#7A5A00]">{VERIF[user.verification_status] || user.verification_status}</span>}</div><p className="mt-1 text-sm text-[#718078]">{user.email}</p><p className="mt-2 text-xs text-[#829087]">Inscrit le {new Date(user.date_joined).toLocaleDateString('fr-FR')} · {user.services_count || 0} prestations · {user.certifications_count || 0} certifications</p>{user.verification_note && <p className="mt-2 text-xs text-[#607067]">Note : {user.verification_note}</p>}</div><div className="flex flex-wrap gap-2">{user.is_active ? <button onClick={() => action(user,'suspend')} className="rounded-2xl border border-[#E8C4BF] px-3 py-2 text-xs font-black text-[#B23A31]">Suspendre</button> : <button onClick={() => action(user,'reactivate')} className="rounded-2xl bg-[#EAF4F0] px-3 py-2 text-xs font-black text-[#0B6B50]">Réactiver</button>}{user.role === 'artisan' && user.verification_status !== 'verified' && <button onClick={() => action(user,'verify')} className="rounded-2xl bg-[#0B6B50] px-3 py-2 text-xs font-black text-white">Vérifier</button>}{user.role === 'artisan' && user.verification_status !== 'rejected' && <button onClick={() => action(user,'reject')} className="rounded-2xl bg-[#F7F8F6] px-3 py-2 text-xs font-black">Refuser vérification</button>}</div></div></article>)}</div>
  </div>;
}
