import { useEffect, useState } from 'react';
import axios from '../../utils/axiosInstance';

export default function AdminCertificationsPage() {
  const [items, setItems] = useState([]); const [status, setStatus] = useState('pending'); const [message, setMessage] = useState('');
  const load = async () => { try { const r = await axios.get('/certifications/admin/', { params: status ? { status } : {} }); setItems(r.data || []); } catch { setMessage('Impossible de charger les certifications.'); } };
  useEffect(() => { load(); }, [status]);
  const review = async (item, action) => { const note = window.prompt(action === 'reject' ? 'Motif du refus' : 'Note (facultative)', '') || ''; try { await axios.post(`/certifications/admin/${item.id}/review/`, { action, note }); setMessage('Certification mise à jour.'); await load(); } catch (e) { setMessage(e?.response?.data?.detail || 'Action impossible.'); } };
  return <div className="mx-auto max-w-[1350px] space-y-6 p-4 sm:p-6 lg:p-8"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#0B6B50]">Confiance</p><h1 className="mt-2 text-3xl font-black">Vérification des certifications</h1></div>{message && <p className="rounded-2xl bg-[#EDF4FF] p-3 text-sm font-semibold text-[#3565A8]">{message}</p>}<select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-2xl border border-black/10 bg-white px-4 py-3 text-sm"><option value="pending">Soumises</option><option value="in_review">En vérification</option><option value="verified">Vérifiées</option><option value="rejected">Refusées</option><option value="">Toutes</option></select><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <article key={item.id} className="rounded-[26px] border border-black/5 bg-white p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-black">{item.nom}</h2><p className="text-sm text-[#718078]">{item.organisme}</p><p className="mt-1 text-xs font-bold text-[#0B6B50]">Artisan : {item.artisan_username}</p></div><span className="rounded-full bg-[#F1F4F2] px-2 py-1 text-xs font-bold">{item.status_label}</span></div>{item.fichier && <a href={item.fichier} target="_blank" rel="noreferrer" className="mt-4 inline-flex rounded-xl bg-[#EDF4FF] px-3 py-2 text-xs font-black text-[#3565A8]">Ouvrir le justificatif ↗</a>}{item.review_note && <p className="mt-3 rounded-xl bg-[#F7F8F6] p-3 text-xs">{item.review_note}</p>}<div className="mt-4 flex flex-wrap gap-2"><button onClick={() => review(item,'review')} className="rounded-xl border border-black/10 px-3 py-2 text-xs font-bold">Mettre en analyse</button><button onClick={() => review(item,'verify')} className="rounded-xl bg-[#0B6B50] px-3 py-2 text-xs font-black text-white">Valider</button><button onClick={() => review(item,'reject')} className="rounded-xl bg-[#FFF0EE] px-3 py-2 text-xs font-black text-[#B23A31]">Refuser</button></div></article>)}</div>{items.length===0 && <p className="rounded-2xl bg-white p-5 text-sm text-[#718078]">Aucune certification dans cette catégorie.</p>}</div>;
}
