# Generated by Django 5.2 on 2025-04-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
