# Generated by Django 5.2 on 2025-04-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='commentaire_client',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='methode_paiement',
            field=models.CharField(blank=True, choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('mtn_money', 'MTN Money'), ('espèces', 'Espèces'), ('autre', 'Autre')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='note_client',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
