# Generated by Django 5.2 on 2025-05-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
