# Generated by Django 5.2 on 2025-04-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation',
            name='titre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
