# Generated by Django 5.2.17 on 2026-09-25 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_realisation_titre'),
        ('portfolio', '0002_portfolio_photo_profil'),
    ]

    operations = [
    ]
