# Generated by Django 5.2 on 2025-05-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='categorie',
            field=models.CharField(choices=[('alimentation', 'Alimentation'), ('artisanat_d_art', 'Artisanat d’Art'), ('btp', 'Bâtiment et Travaux Publics'), ('bois', 'Bois et dérivés'), ('cuir', 'Cuir et Peaux'), ('coiffure_esthetique', 'Coiffure et Esthétique'), ('couture_habillement', 'Couture et Habillement'), ('electronique', 'Électronique et Électromécanique'), ('energie_renouvelable', 'Énergie Renouvelable'), ('mecanique_auto', 'Mécanique et Réparation Automobile'), ('metallurgie_soudure', 'Métallurgie et Soudure'), ('savonnerie', 'Production de savon et produits ménagers'), ('serigraphie', 'Sérigraphie et Impression'), ('services_numeriques', 'Services Numériques'), ('transport', 'Transport et Logistique Artisanale')], max_length=50),
        ),
    ]
